import { spawn, type ChildProcess } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import * as readline from 'readline';
import type { AgentCallbacks } from '../agent';
import { logger } from '@shofferai/shared';
// CredentialVault interface — duck-typed to avoid package dependency
interface CredentialVault {
  getFieldValue(credentialId: string, userId: string, fieldType: string): Promise<string>;
}
import { SCRIPT_CODE, SKILL_ID, REQUIRED_PARAMS } from './compiled/booking-com-hotel';
import { ScriptStore } from './store';

/** Registry of hand-written compiled scripts (code strings + metadata) */
const COMPILED_SCRIPTS: Record<string, { code: string; requiredParams: string[] }> = {
  [SKILL_ID]: { code: SCRIPT_CODE, requiredParams: REQUIRED_PARAMS },
};

/**
 * ScriptPlayer — runs compiled Playwright scripts as child processes.
 * Supports bidirectional communication via stdin/stdout for interactive flows
 * (credential filling, user confirmation, OTP handling).
 *
 * Loads scripts from two sources:
 * 1. COMPILED_SCRIPTS — hand-written, hardcoded (e.g., booking-com-hotel)
 * 2. ScriptStore — auto-generated by ScriptCompiler from MCP recordings
 */
export class ScriptPlayer {
  constructor(
    private skillId: string,
    private params: Record<string, string>,
    private callbacks: AgentCallbacks,
    private userContext?: Record<string, unknown>,
    private vault?: CredentialVault,
    private userId?: string
  ) {}

  /**
   * Check if a compiled script exists for the given skill.
   * Checks both hardcoded registry and auto-generated store.
   */
  static hasScript(skillId: string): boolean {
    if (skillId in COMPILED_SCRIPTS) return true;

    // Synchronous check for auto-generated scripts
    // (ScriptStore methods are async but we need sync here — check file existence directly)
    try {
      const candidates = [
        path.join(__dirname, 'compiled'),
        path.resolve(process.cwd(), 'packages/agent-core/src/scripts/compiled'),
        path.resolve(process.cwd(), '../../packages/agent-core/src/scripts/compiled'),
      ];
      for (const dir of candidates) {
        const codeFile = path.join(dir, `${skillId}.generated.js`);
        const metaFile = path.join(dir, `${skillId}.generated.meta.json`);
        if (fs.existsSync(codeFile) && fs.existsSync(metaFile)) {
          return true;
        }
      }
    } catch { /* ignore */ }

    return false;
  }

  async play(): Promise<{ completed: boolean; error?: string }> {
    // Try hardcoded registry first
    let entry = COMPILED_SCRIPTS[this.skillId];

    // Fall back to auto-generated scripts from store
    if (!entry) {
      const stored = await ScriptStore.loadCode(this.skillId);
      if (stored) {
        entry = stored;
        logger.info('Using auto-generated script from store', { skillId: this.skillId });
      }
    }

    if (!entry) {
      return { completed: false, error: 'No compiled script found' };
    }

    logger.info('Running native Playwright script via child process', {
      skillId: this.skillId,
      params: this.params,
    });

    this.callbacks.onStepUpdate({
      action: 'Running cached workflow (instant mode)',
      status: 'running',
    });

    // Write script to temp file and execute it
    const tmpFile = path.join(os.tmpdir(), `shofferai-script-${Date.now()}.js`);
    fs.writeFileSync(tmpFile, entry.code);

    try {
      const result = await this.runScript(tmpFile, this.params, this.userContext || {});
      return result;
    } finally {
      // Cleanup temp file
      try { fs.unlinkSync(tmpFile); } catch { /* ignore */ }
    }
  }

  /** Send a JSON message to the child process via stdin */
  private sendToChild(child: ChildProcess, data: Record<string, unknown>): void {
    if (child.stdin && !child.stdin.destroyed) {
      child.stdin.write(JSON.stringify(data) + '\n');
    }
  }

  /** Handle interactive messages from the script that require a response */
  private async handleInteractiveMessage(
    msg: Record<string, unknown>,
    child: ChildProcess
  ): Promise<boolean> {
    // confirm_action: Ask user to confirm before payment
    if (msg.type === 'confirm_action') {
      this.callbacks.onStepUpdate({
        action: `Confirming: ${msg.action}`,
        status: 'paused_for_input',
      });
      const confirmed = await this.callbacks.onConfirmRequired({
        action: msg.action as string,
        description: (msg.details as string) || '',
      });
      this.sendToChild(child, { confirmed });
      return true;
    }

    // fill_credential: Securely fill a form field with encrypted credential
    if (msg.type === 'fill_credential') {
      this.callbacks.onStepUpdate({
        action: 'Filling secure credential field',
        status: 'running',
      });

      if (!this.vault || !this.userId) {
        this.sendToChild(child, { error: 'Credential vault not available' });
        return true;
      }

      try {
        const value = await this.vault.getFieldValue(
          msg.credentialId as string,
          this.userId,
          msg.fieldType as string
        );
        // Send decrypted value through stdin pipe (in-memory, never logged)
        this.sendToChild(child, { value });
        logger.info('Credential value sent to script', {
          fieldType: msg.fieldType,
          // Never log the actual value
        });
      } catch (error) {
        const errMsg = error instanceof Error ? error.message : 'Credential retrieval failed';
        logger.error('Failed to retrieve credential for script', { error: errMsg });
        this.sendToChild(child, { error: errMsg });
      }
      return true;
    }

    // payment_required: Pause for L2 payment panel (Razorpay)
    if (msg.type === 'payment_required') {
      this.callbacks.onStepUpdate({
        action: `Payment required: ${msg.action || 'Complete booking'}`,
        status: 'paused_for_input',
      });

      if (this.callbacks.onPaymentRequired) {
        const confirmed = await this.callbacks.onPaymentRequired({
          bookingSummary: (msg.bookingSummary as string) || '',
          amountInr: (msg.amountInr as number) || 0,
          description: (msg.description as string) || '',
        });
        this.sendToChild(child, { confirmed });
      } else {
        // Fallback to confirm_action if no payment handler
        const confirmed = await this.callbacks.onConfirmRequired({
          action: (msg.action as string) || 'Complete booking payment',
          description: (msg.details as string) || '',
        });
        this.sendToChild(child, { confirmed });
      }
      return true;
    }

    // input_required: Ask user for OTP, choice, or freetext
    if (msg.type === 'input_required') {
      this.callbacks.onStepUpdate({
        action: msg.question as string,
        status: 'paused_for_input',
      });
      const response = await this.callbacks.onInputRequired({
        taskId: '',
        stepId: `script-${Date.now()}`,
        question: msg.question as string,
        inputType: (msg.inputType as 'otp' | 'confirmation' | 'choice' | 'freetext') || 'freetext',
        options: msg.options as string[] | undefined,
      });
      this.sendToChild(child, { value: response.value });
      return true;
    }

    return false;
  }

  private runScript(
    scriptPath: string,
    params: Record<string, string>,
    userContext: Record<string, unknown>
  ): Promise<{ completed: boolean; error?: string }> {
    return new Promise((resolve) => {
      // Find monorepo root node_modules for playwright
      let nodeModules = path.resolve(process.cwd(), 'node_modules');
      if (!fs.existsSync(path.join(nodeModules, 'playwright'))) {
        nodeModules = path.resolve(process.cwd(), '../../node_modules');
      }

      const child = spawn('node', [scriptPath, JSON.stringify(params), JSON.stringify(userContext)], {
        stdio: ['pipe', 'pipe', 'pipe'],
        env: {
          ...process.env,
          NODE_PATH: nodeModules,
          CHROME_CDP_ENDPOINT: process.env.CHROME_CDP_ENDPOINT || 'http://localhost:9222',
        },
      });

      let errorOutput = '';

      // Use readline for line-by-line stdout processing
      const rl = readline.createInterface({ input: child.stdout! });

      rl.on('line', async (line: string) => {
        if (!line.trim()) return;
        try {
          const msg = JSON.parse(line);

          // Try interactive message handlers first
          const handled = await this.handleInteractiveMessage(msg, child);
          if (handled) return;

          // Standard message handlers
          if (msg.step) {
            this.callbacks.onStepUpdate({
              action: msg.step,
              status: msg.status || 'running',
            });
          }
          if (msg.message) {
            this.callbacks.onMessage(msg.message);
          }
          if (msg.done) {
            this.callbacks.onComplete('Workflow completed via native script.');
          }
          if (msg.error) {
            errorOutput = msg.error;
          }
        } catch {
          // Non-JSON output, ignore
        }
      });

      child.stderr!.on('data', (data: Buffer) => {
        errorOutput += data.toString();
      });

      child.on('close', (code) => {
        rl.close();
        if (code === 0) {
          resolve({ completed: true });
        } else {
          logger.warn('Script child process failed', { code, error: errorOutput });
          resolve({ completed: false, error: errorOutput || `Exit code ${code}` });
        }
      });

      child.on('error', (err) => {
        rl.close();
        resolve({ completed: false, error: err.message });
      });
    });
  }
}
