import * as fs from 'fs';
import * as path from 'path';
import type { SkillScript } from './types';
import { logger } from '@shofferai/shared';

// Use a reliable path — resolve from the package root, not __dirname (which breaks in webpack)
function getCompiledDir(): string {
  // Try multiple paths to find the compiled directory
  const candidates = [
    path.join(__dirname, 'compiled'),
    path.resolve(process.cwd(), 'packages/agent-core/src/scripts/compiled'),
    path.resolve(process.cwd(), '../../packages/agent-core/src/scripts/compiled'),
  ];

  for (const dir of candidates) {
    if (fs.existsSync(dir)) return dir;
  }

  // Default — create if needed
  const defaultDir = path.resolve(process.cwd(), 'packages/agent-core/src/scripts/compiled');
  return defaultDir;
}

export class ScriptStore {
  static async load(skillId: string): Promise<SkillScript | null> {
    try {
      const compiledDir = getCompiledDir();
      logger.debug('Looking for compiled scripts', { dir: compiledDir, skillId });

      if (!fs.existsSync(compiledDir)) {
        logger.debug('Compiled directory not found', { dir: compiledDir });
        return null;
      }

      const files = fs.readdirSync(compiledDir)
        .filter((f) => f.startsWith(`${skillId}.v`) && f.endsWith('.json'))
        .sort();

      if (files.length === 0) {
        logger.debug('No compiled scripts found for skill', { skillId });
        return null;
      }

      const latest = files[files.length - 1];
      const filepath = path.join(compiledDir, latest);
      const content = fs.readFileSync(filepath, 'utf-8');
      const script = JSON.parse(content) as SkillScript;

      logger.info('Loaded compiled script', {
        skillId,
        file: latest,
        format: script.format || 'legacy',
        steps: script.steps?.length || script.actions?.length || 0,
      });
      return script;
    } catch (error) {
      logger.warn('Failed to load compiled script', { skillId, error });
      return null;
    }
  }

  static async save(script: SkillScript): Promise<string> {
    const compiledDir = getCompiledDir();

    if (!fs.existsSync(compiledDir)) {
      fs.mkdirSync(compiledDir, { recursive: true });
    }

    // Auto-increment version: find highest existing version and bump
    const existingFiles = fs.readdirSync(compiledDir)
      .filter((f) => f.startsWith(`${script.skillId}.v`) && f.endsWith('.json'));

    let maxVersion = 0;
    for (const f of existingFiles) {
      const match = f.match(/\.v(\d+)\.json$/);
      if (match) maxVersion = Math.max(maxVersion, parseInt(match[1], 10));
    }
    script.version = maxVersion + 1;

    // Remove old version files — only keep the latest (self-healing)
    for (const f of existingFiles) {
      try {
        fs.unlinkSync(path.join(compiledDir, f));
        logger.debug('Removed old script version', { file: f });
      } catch { /* ignore */ }
    }

    const filename = `${script.skillId}.v${script.version}.json`;
    const filepath = path.join(compiledDir, filename);

    fs.writeFileSync(filepath, JSON.stringify(script, null, 2));
    logger.info('Saved compiled script', { skillId: script.skillId, file: filename, version: script.version });

    // Also save the compiled Playwright code as a standalone .js file
    if (script.compiledCode) {
      await this.saveCode(script.skillId, script.compiledCode, script.requiredParams);
    }

    return filepath;
  }

  /**
   * Save auto-compiled native Playwright code as a standalone .js file.
   * This can be loaded directly by ScriptPlayer without the JSON wrapper.
   */
  static async saveCode(
    skillId: string,
    code: string,
    requiredParams: string[]
  ): Promise<string> {
    const compiledDir = getCompiledDir();

    if (!fs.existsSync(compiledDir)) {
      fs.mkdirSync(compiledDir, { recursive: true });
    }

    // Save as a .generated.js file (distinct from hand-written .ts files)
    const filename = `${skillId}.generated.js`;
    const filepath = path.join(compiledDir, filename);

    // Add metadata header
    const header = [
      '// Auto-generated by ShofferAI ScriptCompiler',
      `// Skill: ${skillId}`,
      `// Generated: ${new Date().toISOString()}`,
      `// Required params: ${requiredParams.join(', ')}`,
      '// DO NOT EDIT — this file is regenerated from MCP recordings',
      '',
    ].join('\n');

    fs.writeFileSync(filepath, header + code);
    logger.info('Saved compiled Playwright code', { skillId, file: filename });

    // Also save a metadata sidecar for loading
    const metaFilename = `${skillId}.generated.meta.json`;
    const metaFilepath = path.join(compiledDir, metaFilename);
    fs.writeFileSync(metaFilepath, JSON.stringify({
      skillId,
      requiredParams,
      generatedAt: new Date().toISOString(),
      codeFile: filename,
    }, null, 2));

    return filepath;
  }

  /**
   * Load auto-compiled native Playwright code for a skill.
   * Returns the code string + required params, or null if not found.
   */
  static async loadCode(skillId: string): Promise<{ code: string; requiredParams: string[] } | null> {
    try {
      const compiledDir = getCompiledDir();

      // First check for .generated.js files (auto-compiled)
      const codeFile = path.join(compiledDir, `${skillId}.generated.js`);
      const metaFile = path.join(compiledDir, `${skillId}.generated.meta.json`);

      if (fs.existsSync(codeFile) && fs.existsSync(metaFile)) {
        const code = fs.readFileSync(codeFile, 'utf-8');
        const meta = JSON.parse(fs.readFileSync(metaFile, 'utf-8'));
        logger.info('Loaded auto-generated script code', { skillId });
        return { code, requiredParams: meta.requiredParams || [] };
      }

      // Fall back to checking SkillScript JSON for compiledCode field
      const script = await this.load(skillId);
      if (script?.compiledCode) {
        logger.info('Loaded compiled code from SkillScript JSON', { skillId });
        return { code: script.compiledCode, requiredParams: script.requiredParams };
      }

      return null;
    } catch (error) {
      logger.warn('Failed to load compiled code', { skillId, error });
      return null;
    }
  }

  static async exists(skillId: string): Promise<boolean> {
    const script = await this.load(skillId);
    return script !== null;
  }

  /**
   * Check if auto-compiled native code exists for a skill.
   */
  static async hasCode(skillId: string): Promise<boolean> {
    const code = await this.loadCode(skillId);
    return code !== null;
  }
}
