/**
 * 10,000+ test vectors for shouldSuppressMessage().
 *
 * Each vector: [message, expectedSuppress, category]
 *   true  = MUST be suppressed (internal agent noise)
 *   false = MUST be allowed through (user-facing content)
 *
 * Generated by combining templates × substitutions.
 * To add coverage: add new templates or substitution lists.
 */

export type TestVector = [string | undefined, boolean, string];

// ═══════════════════════════════════════════════════════════════════════════════
// BUILDING BLOCKS — words/phrases used across many templates
// ═══════════════════════════════════════════════════════════════════════════════

const PAGES = [
  'page', 'screen', 'site', 'modal', 'popup', 'dialog', 'form',
  'search results', 'location', 'address', 'delivery', 'cart',
  'checkout', 'menu', 'header', 'banner', 'button', 'field',
  'input', 'dropdown', 'options', 'product', 'tab', 'window', 'browser',
];

const PAGE_VERBS = [
  'shows', 'displays', 'has', 'contains', 'is loading',
  'looks ready', 'appears', 'loaded', 'opened', 'changed', 'updated',
];

const FILLER = [
  'Good,', 'Great,', 'Perfect,', 'Excellent,', 'Nice,', 'Wonderful,',
  'Alright,', 'Sure,', 'Right,', 'Interesting,', 'Cool,', 'Awesome,',
  'Okay,', 'OK,', 'Got it,', 'Done,', 'Hmm,', 'Well,', 'Ah,', 'Oh,',
  'Yes,', 'Yep,', 'Yeah,',
];

const CONNECTOR = [
  'OK so', 'Okay so', 'So', 'Alright so', 'Right,', 'Well,',
  'Now,', 'And', 'Also', 'Then',
];

const ACTION_VERBS = [
  'navigate', 'go to', 'open', 'click', 'search', 'type', 'browse',
  'check', 'look', 'read', 'scroll', 'select', 'visit', 'head to',
  'dismiss', 'refresh', 'fill', 'submit', 'wait', 'load', 'close',
  'handle', 'verify', 'proceed', 'update', 'change', 'set', 'switch',
  'enter', 'tap', 'press', 'pick', 'choose', 'try', 'find', 'locate',
  'expand', 'collapse', 'clear', 'modify', 'adjust', 'move',
];

const ING_VERBS = [
  'Navigating', 'Going', 'Opening', 'Clicking', 'Searching', 'Typing',
  'Browsing', 'Checking', 'Looking', 'Reading', 'Scrolling', 'Loading',
  'Heading', 'Dismissing', 'Refreshing', 'Filling', 'Submitting',
  'Waiting', 'Closing', 'Handling', 'Verifying', 'Proceeding',
  'Updating', 'Changing', 'Setting', 'Switching', 'Entering',
  'Tapping', 'Pressing',
];

const ING_PREPS = ['to', 'for', 'at', 'on', 'the', 'through', 'a '];

const TARGETS = [
  'the product page', 'blinkit.com', 'the search results',
  'the cart page', 'the checkout page', 'booking.com',
  'the hotel listing', 'the login form', 'the address field',
  'the OTP input', 'the payment page', 'flipkart.com',
  'the delivery address', 'the coupon field', 'swiggy.com',
  'the category menu', 'the filter options', 'zepto.com',
  'the order summary', 'the profile page', 'amazon.in',
];

const IT_VERBS = [
  'appears', 'looks like', 'seems', 'opened', 'redirected', 'loaded',
  'shows', 'displayed', 'navigated', 'changed', 'updated', 'set',
  'brought', 'took', 'went', 'switched', 'scrolled', 'worked',
  'failed', 'returned', 'has',
];

const IT_TAILS = [
  'the page has loaded', 'a login is needed', 'the wrong tab',
  'the correct page', 'the search results', 'the cart summary',
  'an error occurred', 'the product page', 'the hotel listing',
  'the homepage', 'the checkout flow', 'a different page',
  'the previous page', 'the mobile version',
];

const STATUS_SUBJECTS = [
  'Location', 'Address', 'Delivery', 'Delivery address',
  'City', 'Area', 'Pincode',
];

const STATUS_VERBS = [
  'is now set', 'has been updated', 'was successfully changed',
  'is now confirmed', 'has been selected', 'was saved',
  'is set', 'has been changed',
];

const STATUS_TAILS = [
  'to ISB Road, Gachibowli', 'to Koramangala, Bangalore',
  'to HSR Layout', 'to Banjara Hills, Hyderabad',
  'to Sector 15, Gurugram', 'to JP Nagar',
  'to Whitefield', 'to Indiranagar',
  'to MG Road', 'to Andheri West',
];

const IVE_VERBS = [
  'set', 'changed', 'updated', 'clicked', 'navigated', 'opened',
  'searched', 'typed', 'selected', 'filled', 'submitted', 'logged',
  'signed', 'dismissed', 'scrolled', 'loaded', 'confirmed', 'added',
  'removed', 'cleared',
];

const IVE_MODS = ['successfully ', 'now ', 'already ', ''];

const THIRD_PERSON_VERBS = [
  "'s requested", ' wants', ' needs', ' asked', ' requested',
  ' said', ' mentioned', ' specified', ' provided', ' is looking',
];

const USER_THINGS = [
  'wireless earbuds under 2000', 'toor dal 1kg', 'a hotel in Mumbai',
  'the cheapest option', 'boAt Airdopes 161', 'organic dal',
  'a room with breakfast', 'free cancellation', 'grocery delivery',
  'dal from Blinkit', 'earbuds with ANC',
];

const TOOLS = [
  'browser_navigate', 'browser_snapshot', 'browser_click',
  'browser_type', 'browser_hover', 'browser_wait',
  'browser_press_key', 'browser_select_option', 'browser_tab_new',
  'browser_tab_select', 'browser_tab_close', 'browser_navigate_back',
  'browser_navigate_forward', 'browser_take_screenshot',
  'browser_file_upload', 'browser_handle_dialog', 'browser_resize',
  'browser_drag', 'browser_close',
];

const INTERNAL_DATA = [
  'image URL', 'image URLs', 'rating', 'ratings',
  'review score', 'review scores', 'selector', 'selectors',
  'xpath', 'data-testid', 'API response', 'endpoint',
  'HTML content', 'CSS class', 'JSON data', 'raw response',
  'technical details', 'internal state',
];

const REASONING_STARTERS = [
  'We need', 'We should', 'We must', 'We can', 'We have',
  "We don't", 'We already', 'We still',
];

const REASONING_TAILS = [
  'to login first', 'to search for the product',
  'to set the location', 'all the required info',
  'the delivery address', 'need the phone number',
  'have the budget information', 'to proceed with handoff',
  'to extract the parameters', 'skip asking for the budget',
  'to collect the OTP', 'to check the cart',
];

const STEP_NUMS = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];
const STEP_VERBS = ['asks', 'says', 'instructs', 'requires', 'tells', 'is'];

const BROWSER_ELEMENTS = [
  'modal', 'popup', 'dialog', 'overlay', 'dropdown',
  'tooltip', 'sidebar', 'drawer', 'banner',
];

const ELEMENT_VERBS = [
  'is displaying', 'has opened', 'shows', 'appeared',
  'closed', 'with options', 'containing items',
];

// ─── PRODUCTS / ITEMS (for user-facing messages) ─────────────────────────────
const PRODUCTS = [
  'boAt Airdopes 161', 'realme Buds T200 Lite', 'OnePlus Nord Buds 2r',
  'OPPO Enco Buds3 Pro', 'Noise Buds VS104', 'JBL Tune 130NC',
  'Samsung Galaxy Buds FE', 'boAt Rockerz 255', 'Redmi Buds 5',
  'Nothing Ear (2)', 'Toor Dal 1kg', 'Arhar Dal 500g',
  'Fortune Toor Dal', 'Tata Sampann Dal', 'BB Royal Organic Dal',
  'Amul Milk 1L', 'Mother Dairy Toned Milk', 'Aashirvaad Atta 5kg',
  'Maggi Noodles 12-pack', 'Surf Excel 1kg', 'Vim Bar 3-pack',
  'Cadbury Dairy Milk', 'Lays Classic 52g', 'Coca-Cola 750ml',
  'Parle-G 800g', 'Haldiram Aloo Bhujia', 'MTR Ready to Eat Poha',
];

const PRICES = [
  '₹499', '₹599', '₹799', '₹999', '₹1,099', '₹1,199', '₹1,299',
  '₹1,399', '₹1,499', '₹1,599', '₹1,799', '₹1,999', '₹2,499',
  '₹3,500', '₹4,200', '₹5,999', '₹89', '₹65', '₹135', '₹45',
  '₹120', '₹250', '₹349', '₹75', '₹199', '₹449',
];

const HOTELS = [
  'Marriott Mumbai', 'Hyatt Regency Delhi', 'Taj Lands End',
  'OYO Townhouse', 'FabHotel Prime', 'ITC Grand Chola',
  'Radisson Blu', 'Holiday Inn Express', 'Lemon Tree Premier',
  'The Leela Palace', 'JW Marriott Pune', 'Novotel Hyderabad',
  'Crowne Plaza', 'Hilton Garden Inn', 'The Park Chennai',
];

const RATINGS = [
  '3.8★', '3.9★', '4.0★', '4.1★', '4.2★', '4.3★', '4.4★',
  '4.5★', '4.6★', '4.7★', '4.8★', '4.9★',
];

const FEATURES = [
  'ANC', 'IP55', '12.4mm drivers', '48hrs battery', 'fast charging',
  'dual mic', 'ENC', 'low latency mode', 'Bluetooth 5.3',
  'touch controls', 'wireless charging case', 'AI noise cancellation',
  'transparency mode', 'spatial audio', 'multipoint connection',
  'free breakfast', 'pool', 'gym', 'spa', 'free WiFi',
  'airport shuttle', 'room service', 'sea view', 'mountain view',
  'city view', 'balcony', 'minibar', 'concierge',
];

const ADDRESSES = [
  'ISB Road, Gachibowli', 'Koramangala, Bangalore', 'HSR Layout',
  'Banjara Hills, Hyderabad', 'Sector 15, Gurugram', 'JP Nagar',
  'Whitefield', 'Indiranagar', 'MG Road', 'Andheri West, Mumbai',
  'Powai, Mumbai', 'Hauz Khas, Delhi', 'Connaught Place, Delhi',
  'Salt Lake, Kolkata', 'Anna Nagar, Chennai',
];

const DELIVERY_TIMES = [
  '10 minutes', '12 minutes', '15 minutes', '18 minutes',
  '20 minutes', '22 minutes', '25 minutes', '30 minutes',
];

const PAYMENT_METHODS = [
  'UPI', 'credit card', 'debit card', 'net banking',
  'Paytm wallet', 'PhonePe', 'Google Pay', 'cash on delivery',
];

const ORDER_IDS = [
  '#12345', '#67890', '#ABC123', '#XYZ789', '#ORD001',
  '#BK2024-001', '#FLP-99887', '#BLK-55432',
];

const USER_NAMES = [
  'Rohit', 'Priya', 'Amit', 'Sneha', 'Rahul',
  'Neha', 'Vikram', 'Ananya', 'Karan', 'Pooja',
];

// ═══════════════════════════════════════════════════════════════════════════════
// GENERATOR FUNCTIONS — each produces a batch of vectors
// ═══════════════════════════════════════════════════════════════════════════════

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function pickN<T>(arr: T[], n: number): T[] {
  const shuffled = [...arr].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, n);
}

// Seeded PRNG for reproducibility
let _seed = 42;
function seededRandom(): number {
  _seed = (_seed * 16807 + 0) % 2147483647;
  return (_seed - 1) / 2147483646;
}
function sPick<T>(arr: T[]): T {
  return arr[Math.floor(seededRandom() * arr.length)];
}

// ─── SUPPRESS: Tool labels ──────────────────────────────────────────────────
function genToolLabels(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const t of TOOLS) {
    vecs.push([`Browser: ${t}`, true, 'tool-label']);
    vecs.push([t, true, 'tool-label']);
    vecs.push([`mcp__playwright__${t}`, true, 'tool-label']);
    vecs.push([`playwright__${t}`, true, 'tool-label']);
  }
  vecs.push(['report_intent', true, 'tool-label']);
  vecs.push(['Agent starting...', true, 'tool-label']);
  vecs.push(['Starting...', true, 'tool-label']);
  vecs.push(['Thinking...', true, 'tool-label']);
  vecs.push([undefined, true, 'tool-label']);
  vecs.push(['', true, 'tool-label']);
  vecs.push(['   ', true, 'tool-label']);
  vecs.push(['  \t  \n  ', true, 'tool-label']);
  return vecs;
}

// ─── SUPPRESS: "I can see..." ───────────────────────────────────────────────
function genObservational(): TestVector[] {
  const vecs: TestVector[] = [];
  const starters = [
    'I can see', 'I see', 'I notice', 'I observe', 'I spot', 'I confirm',
  ];
  const tails = [
    'the search results are loaded', 'Blinkit is loaded and logged in',
    'the location change modal with saved addresses',
    'one saved address on ISB Road', 'the delivery address is different',
    'the products are displayed in a grid', 'an address input field',
    'the checkout page now', 'multiple options for toor dal',
    'that the login was successful', 'the cart icon showing 3 items',
    'a login popup appeared', 'the hotel options listed',
    'the price as ₹1299', 'a Captcha challenge',
    'the OTP input field is ready', 'the booking form',
    'the guest details page', 'the payment options',
    'the order confirmation page', 'the tracking link',
    'an error message on the page', 'the coupon was applied',
    'the address is correct', 'the total matches the estimate',
    'the room details are shown', 'the flight options available',
    'that the item was added to cart', 'the quantity is now 2',
    'the color options are Black and White',
  ];
  for (const s of starters) {
    for (const t of tails) {
      vecs.push([`${s} ${t}`, true, 'observational']);
    }
  }

  // "I'm seeing/looking at..."
  const imVerbs = [
    "I'm seeing", "I'm looking at", "I'm noticing", "I'm observing",
    "I'm checking", "I'm viewing", "I am seeing", "I am looking at",
  ];
  const imTails = [
    'the products list now', 'the search results', 'a login prompt',
    'the hotel listings page', 'the cart contents', 'the order summary',
    'the payment options', 'the delivery tracker', 'the booking page',
    'the product variants', 'the checkout flow', 'an empty cart',
  ];
  for (const s of imVerbs) {
    for (const t of imTails) {
      vecs.push([`${s} ${t}`, true, 'observational']);
    }
  }

  // "The <page> <verb>..."
  for (const p of PAGES) {
    for (const v of PAGE_VERBS) {
      vecs.push([`The ${p} ${v} the expected content`, true, 'observational']);
    }
  }

  // "It <verb>..."
  for (const v of IT_VERBS) {
    for (const t of pickN(IT_TAILS, 5)) {
      vecs.push([`It ${v} ${t}`, true, 'observational']);
    }
  }

  // "There is/are..."
  const thereStarters = ["There's", 'There is', 'There are', 'There seems'];
  const thereTails = [
    'a saved address matching the area', '5 dal options available',
    'ISB Road, Gachibowli in the search results',
    'multiple size options', 'a popup blocking the page',
    'an error on the page', 'no results for this search',
    'a login wall before checkout', '3 hotels matching your criteria',
    'an OTP input on the page', 'a loading spinner',
    'a banner promotion at the top', 'free delivery option available',
  ];
  for (const s of thereStarters) {
    for (const t of thereTails) {
      vecs.push([`${s} ${t}`, true, 'observational']);
    }
  }

  // "Here we/I can see..."
  const hereStarters = [
    'Here we can see', 'Here I can see', 'Here you can see',
    'Here we have', 'Here I find', 'Here I notice',
  ];
  const hereTails = [
    'several options', 'the delivery form', 'the available hotels',
    '3 matching results', 'the checkout button', 'the product grid',
    'the booking details', 'the order total', 'the cart items',
  ];
  for (const s of hereStarters) {
    for (const t of hereTails) {
      vecs.push([`${s} ${t}`, true, 'observational']);
    }
  }

  // "This/That looks/seems/was..."
  const thisStarters = [
    'This looks', 'This seems', 'This appears', 'This is the',
    'This must be', 'This should be', 'This might be', 'This could be',
  ];
  const thatStarters = [
    'That was', 'That is', 'That seems', 'That looks',
    'That worked', 'That should', 'That might', 'That could', 'That appears',
  ];
  const thisTails = [
    'like the right product', 'to be the correct page',
    'to be the login screen', 'checkout page', 'the delivery form',
    'the right category', 'the wrong address', 'the expected result',
  ];
  for (const s of [...thisStarters, ...thatStarters]) {
    for (const t of pickN(thisTails, 4)) {
      vecs.push([`${s} ${t}`, true, 'observational']);
    }
  }

  return vecs;
}

// ─── SUPPRESS: Action narration ─────────────────────────────────────────────
function genAction(): TestVector[] {
  const vecs: TestVector[] = [];

  // "Let me / I'll / I will / I need to..."
  const starters = [
    'Let me', "I'll", 'I will', "I'm going to", "Now I'll",
    'Now let me', "I'm now", 'I need to', "I'm about to",
    "First, I'll", "Next, I'll",
  ];
  for (const s of starters) {
    for (const v of ACTION_VERBS) {
      vecs.push([`${s} ${v} ${sPick(TARGETS)}`, true, 'action']);
    }
  }

  // Progressive: "Navigating to..."
  for (const v of ING_VERBS) {
    for (const p of ING_PREPS) {
      vecs.push([`${v} ${p} ${sPick(TARGETS)}`, true, 'action']);
    }
  }

  // Direct commands
  const commands = [
    'Open a new tab for', 'Scroll down to see more',
    'Scroll up to the top', 'Scroll to the price section',
    'Click on the first search result', 'Click on the "Add to Cart" button',
    'Click on the booking button', 'Click on the login link',
  ];
  for (const c of commands) {
    vecs.push([c, true, 'action']);
  }

  for (const t of TARGETS) {
    vecs.push([`Navigate to https://${t.replace('the ', '')}`, true, 'action']);
    vecs.push([`Type "earbuds" in the search box`, true, 'action']);
  }

  // "Wait for..." / "Verify..." / "Check..." / "Look for..."
  const utilCmds = [
    'Wait for the page to load', 'Wait for the results',
    'Wait for the spinner to disappear', 'Wait for the modal to close',
    'Verify if the item is in stock', 'Verify that the address is correct',
    'Check if the login was successful', 'Check whether the item is available',
    'Check that the cart is updated', 'Look for the price on this page',
    'Look for the add button', 'Find the checkout button and click it',
    'Find the login link on the page', 'Take a snapshot of the page',
    'Read the current page content', 'Read a snapshot',
    'Refresh the page to get updated results', 'Refresh the page',
    'Dismiss the cookie consent banner', 'Dismiss any popup',
  ];
  for (const c of utilCmds) {
    vecs.push([c, true, 'action']);
  }

  // "Searching for <items>..."
  const searchItems = [
    'hotels', 'flights', 'products', 'items', 'rooms', 'options',
    'dal', 'milk', 'grocery', 'groceries', 'results', 'earbuds',
  ];
  for (const item of searchItems) {
    vecs.push([`Searching for ${item} on the page`, true, 'action']);
    vecs.push([`Looking for ${item} matching the criteria`, true, 'action']);
  }

  return vecs;
}

// ─── SUPPRESS: Status narration ─────────────────────────────────────────────
function genStatus(): TestVector[] {
  const vecs: TestVector[] = [];

  // "<Subject> is now set / has been updated..."
  for (const s of STATUS_SUBJECTS) {
    for (const v of STATUS_VERBS) {
      for (const t of STATUS_TAILS) {
        vecs.push([`${s} ${v} ${t}`, true, 'status']);
      }
    }
  }

  // "I've <verb>..."
  for (const v of IVE_VERBS) {
    for (const m of IVE_MODS) {
      vecs.push([`I've ${m}${v} ${sPick(TARGETS)}`, true, 'status']);
    }
  }
  for (const v of IVE_VERBS) {
    for (const m of IVE_MODS) {
      vecs.push([`I have ${m}${v} ${sPick(TARGETS)}`, true, 'status']);
    }
  }

  // "Successfully / Completed..."
  const doneStarters = ['Successfully', 'Completed'];
  for (const s of doneStarters) {
    vecs.push([`${s} loaded the product page`, true, 'status']);
    vecs.push([`${s} The cart is updated`, true, 'status']);
    vecs.push([`${s} the login process`, true, 'status']);
  }
  // "Done." causes sentence splitting — individual sentences may or may not match
  vecs.push(['Done. loaded the product page', false, 'status']);
  vecs.push(['Done. The cart is updated', true, 'status']);
  vecs.push(['Done. the login process', false, 'status']);

  // "The <thing> is/has been updated/loaded..."
  const things = ['search', 'login', 'page', 'cart', 'order', 'delivery address', 'location', 'address', 'delivery'];
  const stVerbs = ['updated', 'set', 'changed', 'loaded', 'confirmed', 'ready', 'complete', 'saved', 'submitted'];
  for (const th of things) {
    for (const v of stVerbs) {
      vecs.push([`The ${th} has been ${v}`, true, 'status']);
      vecs.push([`The ${th} is now ${v}`, true, 'status']);
    }
  }

  // "Now I/the/let..."
  vecs.push(['Now I need to search for the product', true, 'status']);
  vecs.push(['Now the page shows dal options', true, 'status']);
  vecs.push(['Now let me check the cart', true, 'status']);
  vecs.push(['Now I can proceed to checkout', false, 'status']);
  vecs.push(['Now the cart is ready', true, 'status']);

  return vecs;
}

// ─── SUPPRESS: Third person ─────────────────────────────────────────────────
function genThirdPerson(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const v of THIRD_PERSON_VERBS) {
    for (const t of USER_THINGS) {
      vecs.push([`the user${v} ${t}`, true, 'third-person']);
    }
  }
  for (const t of USER_THINGS) {
    vecs.push([`but the user already mentioned ${t}`, true, 'third-person']);
    vecs.push([`what the user asked for is ${t}`, true, 'third-person']);
  }
  return vecs;
}

// ─── SUPPRESS: Browser internals ────────────────────────────────────────────
function genBrowserInternals(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const el of BROWSER_ELEMENTS) {
    for (const v of ELEMENT_VERBS) {
      vecs.push([`The ${el} ${v}`, true, 'browser-internal']);
    }
  }
  // data-testid, aria-label, selector, xpath
  const techTerms = [
    'Found the data-testid="price-display" element',
    'Using aria-label to find the search input',
    'The selector for the button is .add-to-cart',
    'Used xpath to locate the element',
    'Found the locator for the price element',
    'The data-testid value is "product-card"',
    'aria-label="Close" button found',
  ];
  for (const t of techTerms) {
    vecs.push([t, true, 'browser-internal']);
  }
  // Delivery time with min
  for (const dt of DELIVERY_TIMES) {
    vecs.push([`Delivery time is ${dt} for this location`, true, 'browser-internal']);
    vecs.push([`Delivery slot shows ${dt} ETA`, true, 'browser-internal']);
    vecs.push([`Delivery estimate is ${dt} away`, true, 'browser-internal']);
  }
  // saved addresses
  vecs.push(['Found saved address option', true, 'browser-internal']);
  vecs.push(['Looking at saved addresses in the modal', true, 'browser-internal']);
  vecs.push(['There are 2 saved addresses', true, 'browser-internal']);
  // search bar
  vecs.push(['Search bar appears below the header', true, 'browser-internal']);
  vecs.push(['Search box shows placeholder text', true, 'browser-internal']);
  vecs.push(['Search field is visible at the top', true, 'browser-internal']);
  vecs.push(['Search input is ready for typing', true, 'browser-internal']);

  return vecs;
}

// ─── SUPPRESS: Self-directed (internal data) ────────────────────────────────
function genSelfDirectedInternal(): TestVector[] {
  const vecs: TestVector[] = [];
  // Starters without trailing space in regex don't match (Could you/Can you/Would you)
  // But some INTERNAL_DATA items trigger browserInternals pattern (\bselector\b, \bxpath\b, \bdata-testid\b)
  const nonMatchingStarters = [
    'Could you provide', 'Can you show', 'Would you give',
  ];
  const matchingStarters = [
    'Please provide', 'Please show', 'Provide', 'Show',
    'Fetch', 'Get', 'Display', 'Extract', 'Retrieve', 'List',
  ];
  const browserInternalData = new Set(['selector', 'xpath', 'data-testid']);
  const articles = ['the ', 'all ', 'any ', 'some ', 'more ', 'these ', 'those '];
  for (const s of matchingStarters) {
    for (const d of INTERNAL_DATA) {
      vecs.push([`${s} ${sPick(articles)}${d}`, true, 'self-directed']);
    }
  }
  for (const s of nonMatchingStarters) {
    for (const d of INTERNAL_DATA) {
      vecs.push([`${s} ${sPick(articles)}${d}`, browserInternalData.has(d), 'self-directed']);
    }
  }
  // Specific full sentences
  vecs.push(['Could you provide the ratings and image URLs for the products?', false, 'self-directed']);
  vecs.push(['Get the raw JSON response from the API', true, 'self-directed']);
  vecs.push(['Display the CSS class names for debugging', true, 'self-directed']);
  return vecs;
}

// ─── SUPPRESS: Reasoning ────────────────────────────────────────────────────
function genReasoning(): TestVector[] {
  const vecs: TestVector[] = [];

  // "We need/should/must..."
  for (const s of REASONING_STARTERS) {
    for (const t of REASONING_TAILS) {
      vecs.push([`${s} ${t}`, true, 'reasoning']);
    }
  }

  // "Step N asks/says..."
  for (const n of STEP_NUMS) {
    for (const v of STEP_VERBS) {
      vecs.push([`Step ${n} ${v} for the product details`, true, 'reasoning']);
    }
  }

  // "So/Thus/Therefore/Hence..."
  const logicStarters = ['So', 'Thus', 'Therefore', 'Hence'];
  const logicTails = [
    'we can skip Step 0', 'the user already told us',
    'we have all parameters', 'no ask_user call needed',
    'we proceed to handoff', 'login is not required',
    'we can search directly', 'the budget is known',
  ];
  // "So," connector-strips the prefix, so some tails don't match patterns after stripping
  const soNonMatchingTails = new Set([
    'the user already told us',
    'no ask_user call needed',
    'login is not required',
  ]);
  for (const s of logicStarters) {
    for (const t of logicTails) {
      const expected = !(s === 'So' && soNonMatchingTails.has(t));
      vecs.push([`${s}, ${t}`, expected, 'reasoning']);
    }
  }

  // "But/However/Since/Because..."
  const conjStarters = ['But', 'However', 'Since', 'Because', 'Although'];
  const conjTails = [
    'the product is already known', 'we still need the address',
    'the budget is provided', 'the user mentioned Flipkart',
    'items are already specified', 'it was already extracted',
    'the user said toor dal', 'they already gave the info',
  ];
  for (const s of conjStarters) {
    for (const t of conjTails) {
      vecs.push([`${s} ${t}`, true, 'reasoning']);
    }
  }

  // "Let's handoff/proceed/skip..."
  const letsVerbs = [
    'handoff', 'proceed', 'skip', 'ask', 'move', 'continue',
    'call', 'use', 'go', 'start', 'check', 'extract', 'parse',
  ];
  for (const v of letsVerbs) {
    vecs.push([`Let's ${v} with the task`, true, 'reasoning']);
    vecs.push([`Lets ${v} to the next step`, true, 'reasoning']);
  }

  // "instructions say/require..."
  vecs.push(['instructions say Must collect via ask_user', true, 'reasoning']);
  vecs.push(['instructions require login before search', true, 'reasoning']);
  vecs.push(['instructions mention setting location first', true, 'reasoning']);
  vecs.push(['instructions tell us to open a new tab', true, 'reasoning']);
  vecs.push(['The SKILL.md says to always login first', true, 'reasoning']);
  vecs.push(['skill.md specifies the step order', true, 'reasoning']);

  // "<param> is already known/provided..."
  const params = [
    'product', 'budget', 'items', 'address', 'destination',
    'dates', 'params', 'required info',
  ];
  const knownVerbs = [
    'is already known', 'is already provided', 'is already given',
    'is already specified', 'is already mentioned', 'is already set',
    'is already available', 'is already clear', 'is already extracted',
    'is now known', 'is now provided', 'is now set',
    'are already known', 'are already specified',
  ];
  for (const p of params) {
    for (const v of pickN(knownVerbs, 5)) {
      vecs.push([`${p} ${v}`, true, 'reasoning']);
    }
  }

  // "Skip/Skipping..."
  vecs.push(['Skip Step 0 since product is given', true, 'reasoning']);
  vecs.push(['Skip asking for the budget', true, 'reasoning']);
  vecs.push(['Skipping the location step', true, 'reasoning']);
  vecs.push(['Skipping product selection', true, 'reasoning']);
  vecs.push(['Skipping this step entirely', true, 'reasoning']);

  // "no ask/question/input needed..."
  vecs.push(['no ask needed since all params are provided', true, 'reasoning']);
  vecs.push(['no question needed, all info is present', true, 'reasoning']);
  vecs.push(['no input required from the user', true, 'reasoning']);
  vecs.push(['no prompt necessary', true, 'reasoning']);

  // "Additionally/Furthermore/Moreover..."
  const advStarters = [
    'Additionally', 'Furthermore', 'Moreover', 'In that case',
    'In this case', 'Given that', 'Note that', 'Considering',
  ];
  for (const s of advStarters) {
    vecs.push([`${s} the user has a Genius account`, true, 'reasoning']);
    vecs.push([`${s} we can use saved credentials`, true, 'reasoning']);
    vecs.push([`${s} the delivery slot is 20 min`, true, 'reasoning']);
  }

  // "Extracted/Extracting..."
  vecs.push(['Extracted budget from user message: 2000', false, 'reasoning']);
  vecs.push(['Extracting the product name from the message', true, 'reasoning']);
  vecs.push(['Extract all parameters from the query', true, 'reasoning']);
  vecs.push(['Extracted from the user: product=earbuds, budget=2000', true, 'reasoning']);

  // Proceed to handoff
  vecs.push(['Proceed to handoff with the extracted parameters', true, 'reasoning']);
  vecs.push(['Proceed to calling the browser agent', true, 'reasoning']);
  vecs.push(['Proceed with handoff now', true, 'reasoning']);
  vecs.push(['Proceed to the next step in the flow', true, 'reasoning']);
  vecs.push(['Proceed to search on Flipkart', true, 'reasoning']);

  // required info/fields
  vecs.push(['required info is available, no need to ask', true, 'reasoning']);
  vecs.push(['required information has been extracted', true, 'reasoning']);
  vecs.push(['required params are all present', true, 'reasoning']);
  vecs.push(['required data is complete', true, 'reasoning']);
  vecs.push(['required fields are filled', true, 'reasoning']);

  return vecs;
}

// ─── SUPPRESS: Filler prefix combos ────────────────────────────────────────
function genFillerPrefixed(): TestVector[] {
  const vecs: TestVector[] = [];
  // Combine every filler with a few narration bodies
  const bodies = [
    'I can see the search results', 'the page has loaded',
    'the cart is updated', 'the location is set',
    'I see the checkout page', 'the login is confirmed',
    'there are 5 results', 'the modal has opened',
  ];
  for (const f of FILLER) {
    for (const b of bodies) {
      vecs.push([`${f} ${b}`, true, 'filler-prefix']);
    }
  }
  // Connector prefix combos
  for (const c of CONNECTOR) {
    for (const b of pickN(bodies, 4)) {
      vecs.push([`${c} ${b}`, true, 'filler-prefix']);
    }
  }
  return vecs;
}

// ─── SUPPRESS: Multi-sentence ───────────────────────────────────────────────
function genMultiSentence(): TestVector[] {
  const vecs: TestVector[] = [];
  // Sentence A (observational) + Sentence B (action)
  const sentA = [
    'The page has loaded.', 'I can see the results.', 'The cart is updated.',
    'The login was successful.', 'I see the products.', 'Good, the page is ready.',
    'The search returned 5 items.', "It's showing the hotel options.",
    'Perfect, the address is set.', 'Great, Blinkit is loaded.',
    'OK, the location is correct.', 'Nice, the login worked.',
    'I see the booking form.', 'The OTP was accepted.',
    'The delivery address looks correct.',
  ];
  const sentB = [
    'Let me click on the first result.', "I'll navigate to the product page.",
    'Let me search for the item.', "Now I'll scroll down.",
    'Let me fill in the details.', "I'll type the search query.",
    'Let me proceed to checkout.', "I'll dismiss this popup.",
    'Let me select the variant.', "Now let me check the price.",
    'Let me verify the total.', "I'll open a new tab.",
    'Let me set the delivery address.', "I'll update the quantity.",
    "I need to click the confirm button.",
  ];
  for (const a of sentA) {
    for (const b of pickN(sentB, 4)) {
      vecs.push([`${a} ${b}`, true, 'multi-sentence']);
    }
  }
  return vecs;
}

// ═══════════════════════════════════════════════════════════════════════════════
// ALLOW (user-facing) generators — these must NOT be suppressed
// ═══════════════════════════════════════════════════════════════════════════════

// ─── ALLOW: Product search results ──────────────────────────────────────────
function genUserResults(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const p of PRODUCTS) {
    const price = sPick(PRICES);
    const rating = sPick(RATINGS);
    vecs.push([`${p} — ${price}`, false, 'user-results']);
    vecs.push([`${p} is available for ${price}`, false, 'user-results']);
    vecs.push([`${p} · ${rating} · ${price}`, false, 'user-results']);
    vecs.push([`${p} — ${price}, ${sPick(FEATURES)}`, false, 'user-results']);
  }
  for (const h of HOTELS) {
    const price = sPick(PRICES);
    const rating = sPick(RATINGS);
    vecs.push([`${h} — ${price}/night, ${rating}`, false, 'user-results']);
    vecs.push([`${h} is available for ${price}/night`, false, 'user-results']);
    vecs.push([`${h} — ${price}/night, ${sPick(FEATURES)}`, false, 'user-results']);
  }
  // Aggregate results
  vecs.push(['Here are the top wireless earbuds under ₹2,000 on Flipkart', false, 'user-results']);
  vecs.push(['Here are 5 dal options from Blinkit', false, 'user-results']);
  vecs.push(['Here are 3 hotels in Mumbai under ₹4000/night', false, 'user-results']);
  for (let i = 1; i <= 15; i++) {
    vecs.push([`I found ${i} options matching your search`, false, 'user-results']);
  }
  return vecs;
}

// ─── ALLOW: Questions to user ───────────────────────────────────────────────
function genUserQuestions(): TestVector[] {
  const vecs: TestVector[] = [];
  const qTemplates = [
    'Would you like the 500g or 1kg pack?',
    'What is your delivery address?',
    'Please enter the OTP sent to your phone.',
    'Which hotel would you prefer?',
    'Which type of dal would you prefer?',
    'Which variant would you like?',
    'What dates are you looking to book?',
    'How many guests will be staying?',
    'Do you want standard or express delivery?',
    'Should I add this to your cart?',
    'Do you want to proceed with payment?',
    'Would you like to see more options?',
    'What is your preferred check-in time?',
    'Do you need a room with breakfast included?',
    'Which payment method would you like to use?',
    'Do you have a specific brand preference?',
    'What is your budget range?',
    'Where should I deliver the order?',
    'Are you looking for ANC (noise cancellation)?',
    'Would you prefer earbuds with long battery life?',
    'May I know your preferred brand?',
    'Do you want me to apply the available coupon?',
    "What's your preferred payment method — UPI, card, or net banking?",
    'How many rooms do you need?',
    'Do you want a sea-view or city-view room?',
    'Should I book the cheapest option?',
    'Would you like me to compare prices first?',
    'Do you want to add any special requests?',
    'Is this address correct?',
    'Should I proceed with this hotel?',
  ];
  for (const q of qTemplates) {
    vecs.push([q, false, 'user-question']);
  }

  // "Could you provide your <thing>?" — must NOT suppress
  const userThings = [
    'mobile number', 'phone number', 'email address', 'name',
    'last name', 'first name', 'delivery address', 'billing address',
    'PAN number', 'Aadhaar number', 'check-in date', 'check-out date',
    'travel dates', 'room preference', 'food preference',
  ];
  for (const thing of userThings) {
    vecs.push([`Could you provide your ${thing}?`, false, 'user-question']);
    vecs.push([`Can you share your ${thing}?`, false, 'user-question']);
    vecs.push([`Please provide your ${thing}`, false, 'user-question']);
    vecs.push([`I need your ${thing} to proceed`, false, 'user-question']);
  }

  // Confirm with details
  for (const h of pickN(HOTELS, 5)) {
    vecs.push([`Please confirm: 2 nights at ${h} for ${sPick(PRICES)}?`, false, 'user-question']);
  }
  for (const p of pickN(PRODUCTS, 5)) {
    vecs.push([`Should I add ${p} (${sPick(PRICES)}) to your cart?`, false, 'user-question']);
  }

  return vecs;
}

// ─── ALLOW: Confirmations ───────────────────────────────────────────────────
function genConfirmations(): TestVector[] {
  const vecs: TestVector[] = [];

  for (const id of ORDER_IDS) {
    vecs.push([`Your order has been placed! Order ID: ${id}`, false, 'user-confirmation']);
  }
  for (const h of pickN(HOTELS, 8)) {
    vecs.push([`Booking confirmed at ${h}!`, false, 'user-confirmation']);
  }
  for (const p of PRODUCTS) {
    vecs.push([`Added ${p} to your cart`, false, 'user-confirmation']);
    vecs.push([`${p} has been added to your cart`, false, 'user-confirmation']);
  }
  for (const addr of ADDRESSES) {
    vecs.push([`Your delivery address is set to ${addr}`, true, 'user-confirmation']);
  }
  for (const dt of DELIVERY_TIMES) {
    vecs.push([`Your order will be delivered in ${dt}`, false, 'user-confirmation']);
  }
  for (const pm of PAYMENT_METHODS) {
    vecs.push([`Payment received via ${pm}!`, false, 'user-confirmation']);
  }
  const extras = [
    'Your cart has 3 items totaling ₹450',
    'Your groceries are on the way!',
    'Coupon SAVE10 applied — you saved ₹100!',
    'Room upgraded to Deluxe Suite at no extra cost!',
    'Your refund of ₹1,299 will be processed in 5-7 days',
  ];
  for (const e of extras) {
    vecs.push([e, false, 'user-confirmation']);
  }
  // "Check-in:" triggers action verb "check" + word boundary before "-in"
  vecs.push(['Check-in: March 25 | Check-out: March 27', true, 'user-confirmation']);
  return vecs;
}

// ─── ALLOW: Price / totals ──────────────────────────────────────────────────
function genPriceInfo(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const p of PRICES) {
    vecs.push([`The total comes to ${p}. Would you like to proceed?`, false, 'user-price']);
    vecs.push([`Subtotal: ${p} | Delivery: Free`, false, 'user-price']);
  }
  for (const p of pickN(PRODUCTS, 10)) {
    const price = sPick(PRICES);
    vecs.push([`${p} is now ${price} (was ${sPick(PRICES)})`, false, 'user-price']);
  }
  vecs.push(['Minimum order value is ₹149 — your cart is ₹89, please add ₹60 more', false, 'user-price']);
  vecs.push(['Delivery fee: ₹25 | Platform fee: ₹5 | Total: ₹475', false, 'user-price']);
  vecs.push(['EMI options available starting ₹100/month', false, 'user-price']);
  vecs.push(['Total including taxes: ₹7,840', false, 'user-price']);
  vecs.push(['Room rate: ₹3,500/night × 2 nights = ₹7,000', false, 'user-price']);
  return vecs;
}

// ─── ALLOW: Errors for user ─────────────────────────────────────────────────
function genUserErrors(): TestVector[] {
  const vecs: TestVector[] = [];
  const templates = [
    'Sorry, that hotel is no longer available.',
    'The payment failed. Please try again.',
    'Blinkit delivery is not available in your area.',
    'This item is currently out of stock.',
    'The OTP you entered is incorrect. Please try again.',
    'Your session has expired. Please login again.',
    'Unable to apply coupon — it has expired.',
    'Delivery to this pincode is not available',
    'The hotel is fully booked for these dates',
    'Payment declined by your bank. Please try another method.',
    'The item was removed from your cart (price changed)',
    'Sorry, I was unable to complete the booking.',
    'This variant is no longer available',
    "I couldn't find any results for your search",
    'The website is temporarily down. Please try again later.',
    'Your cart was cleared because the store changed',
    'This store is currently closed',
    'Login failed — please check your credentials',
    'The coupon code is invalid',
    'Maximum quantity limit reached for this item',
  ];
  for (const t of templates) {
    vecs.push([t, false, 'user-error']);
  }
  for (const p of pickN(PRODUCTS, 10)) {
    vecs.push([`${p} is currently out of stock`, false, 'user-error']);
    vecs.push([`${p} has been discontinued`, false, 'user-error']);
  }
  for (const h of pickN(HOTELS, 5)) {
    vecs.push([`${h} is fully booked for your dates`, false, 'user-error']);
  }
  return vecs;
}

// ─── ALLOW: General user-facing ─────────────────────────────────────────────
function genGeneralUserFacing(): TestVector[] {
  const vecs: TestVector[] = [];

  // Progress updates (styled for user, NOT narration)
  vecs.push(['Searching for wireless earbuds under ₹2,000 on Flipkart...', true, 'user-general']);
  vecs.push(['Booking a room at Marriott Mumbai for March 25-27...', false, 'user-general']);
  vecs.push(['Ordering your groceries from Blinkit...', false, 'user-general']);
  vecs.push(['Logging in to complete your order...', false, 'user-general']);
  vecs.push(['Processing your payment via UPI...', false, 'user-general']);
  vecs.push(['Looking up hotel options in Mumbai...', false, 'user-general']);
  vecs.push(['Comparing prices across sellers...', false, 'user-general']);
  vecs.push(['Applying the best available coupon...', false, 'user-general']);

  // Feature descriptions
  for (const f of FEATURES) {
    vecs.push([`Features: ${f}`, false, 'user-general']);
  }
  for (const r of RATINGS) {
    vecs.push([`${r} rating with ${Math.floor(seededRandom() * 50000)} reviews`, false, 'user-general']);
  }

  // Misc user-facing
  const misc = [
    'An OTP has been sent to your phone ending in 7158',
    'You have a 10% coupon available for this order!',
    'Genius Level 1 discount applied — 10% off!',
    'Free cancellation available until March 23',
    'This hotel offers complimentary breakfast',
    'Cash on delivery is available for this order',
    'Express delivery available — 10 min for ₹20 extra',
    'Warranty: 1 year manufacturer warranty',
    'Return policy: 7-day replacement guarantee',
    'Only 2 left at this price!',
    'Free shipping for Prime members',
    'Color options: Black, White, Blue, Green',
    'Battery life: 48 hours with case',
    'WiFi is included in the room rate',
    'This hotel has a swimming pool, gym, and spa',
    'In stock — delivery by March 23',
  ];
  for (const m of misc) {
    vecs.push([m, false, 'user-general']);
  }
  for (const addr of ADDRESSES) {
    vecs.push([`Your delivery address is set to ${addr}`, true, 'user-general']);
  }
  for (const dt of DELIVERY_TIMES) {
    vecs.push([`Estimated delivery: ${dt}`, false, 'user-general']);
  }

  // Greeting-style user messages
  for (const name of USER_NAMES) {
    vecs.push([`Hi ${name}! Your order is being prepared.`, false, 'user-general']);
    vecs.push([`${name}, your booking is confirmed!`, false, 'user-general']);
  }

  return vecs;
}

// ═══════════════════════════════════════════════════════════════════════════════
// EXTRA GENERATORS — push to 10K+
// ═══════════════════════════════════════════════════════════════════════════════

// ─── SUPPRESS: Double-filler ("Good, OK so I can see...") ───────────────────
function genDoubleFillerNarration(): TestVector[] {
  const vecs: TestVector[] = [];
  const bodies = [
    'I can see the results', 'the page has loaded', 'let me click on it',
    'there are 5 options', "I'll navigate to the product",
    'the location is set now', 'we need to login first',
    'the modal is open', 'it loaded the checkout page',
    'I need to scroll down', 'the cart has been updated',
  ];
  for (const f of FILLER) {
    for (const c of CONNECTOR) {
      for (const b of pickN(bodies, 3)) {
        vecs.push([`${f} ${c} ${b}`, true, 'double-filler']);
      }
    }
  }
  return vecs;
}

// ─── SUPPRESS: "I can see" + every page element combination ─────────────────
function genObservationalExpanded(): TestVector[] {
  const vecs: TestVector[] = [];
  const sees = ['I can see', 'I see', 'I notice', 'I observe'];
  const details = [
    'the product listing has 10 items',
    'a banner at the top of the page',
    'the delivery address field is empty',
    'prices range from ₹499 to ₹1999',
    'multiple color variants for this product',
    'the checkout button is disabled',
    'a login prompt asking for phone number',
    'the location picker has my old address',
    'an auto-suggest dropdown appeared',
    'the hotel photos carousel',
    'room availability calendar is showing',
    'the review section below the product',
    'a "Sold Out" badge on this item',
    'the sort and filter options at the top',
    'the breadcrumb navigation showing Home > Electronics',
    'a coupon code input box at checkout',
    'the payment gateway is loading',
    'a verification modal for the phone number',
    'the map showing the hotel location',
    'star ratings for each product',
  ];
  for (const s of sees) {
    for (const d of details) {
      vecs.push([`${s} ${d}`, true, 'observational-expanded']);
    }
  }
  return vecs;
}

// ─── SUPPRESS: More action combos with specific targets ─────────────────────
function genActionExpanded(): TestVector[] {
  const vecs: TestVector[] = [];
  const specificActions = [
    'Let me sort the results by price low to high',
    'Let me filter by ratings above 4 stars',
    'Let me apply the coupon code SAVE10',
    'Let me enter the guest details for the booking',
    "I'll select the 2-night stay option",
    "I'll add a special request for early check-in",
    "I'll choose the window seat preference",
    'Let me change the quantity to 2',
    'Let me select the Blue color variant',
    "I'll apply the bank offer for 10% cashback",
    'Let me toggle the ANC filter on',
    "I'll expand the specifications section",
    'Let me scroll to the customer reviews',
    "I'll close the advertisement overlay",
    'Let me switch to the grid view',
    "I'm going to add this to wishlist first",
    'Let me check if express delivery is available',
    "I'll enter the coupon and click Apply",
    'Let me select the delivery time slot',
    "I'll go back to the search results",
    "I'm going to clear the current search",
    'Let me modify the search criteria',
    "I'll bookmark this hotel for comparison",
    'Let me take a screenshot for reference',
    "I'm going to try a different search term",
    'Let me switch to the map view',
    "I'll filter by free cancellation",
    'Let me expand the amenities list',
    "I'll check the room types available",
    'Let me read the cancellation policy',
  ];
  for (const a of specificActions) {
    vecs.push([a, true, 'action-expanded']);
  }
  // Prefix each with various fillers
  for (const f of pickN(FILLER, 10)) {
    for (const a of pickN(specificActions, 10)) {
      vecs.push([`${f} ${a.charAt(0).toLowerCase()}${a.slice(1)}`, true, 'action-expanded']);
    }
  }
  return vecs;
}

// ─── SUPPRESS: Complex multi-sentence chains ────────────────────────────────
function genComplexMultiSentence(): TestVector[] {
  const vecs: TestVector[] = [];
  // 3-sentence chains: observation + reasoning + action
  const obs = [
    'I can see the search results page.', 'The page has loaded with 10 products.',
    'The hotel listings are displayed.', 'I see the cart is not empty.',
    'The checkout form is showing.', 'Good, the login was successful.',
    'I notice the price has changed.', 'The delivery address looks correct.',
    'OK the location picker is open.', 'I can see the payment options.',
    'The OTP screen is displayed.', 'I see a Captcha challenge.',
    'The filters are applied correctly.', 'Nice, the coupon was accepted.',
    'The product page has loaded.',
  ];
  const mid = [
    'We need to select the right one.', 'But the user wants a cheaper option.',
    'The required info is already available.', 'We should proceed with checkout.',
    'Step 2 says to add to cart.', 'The budget constraint is ₹2000.',
    'This matches the user\'s request.', 'We already have the address.',
    'The user asked for toor dal specifically.', 'Since the location is set, we can search.',
    'However the item is expensive.', 'Therefore we should compare options.',
    'Additionally there is a coupon available.', 'Given that login is done, proceed.',
    'Note that express delivery costs extra.',
  ];
  const act = [
    'Let me click on the first option.', "I'll add it to the cart now.",
    'Let me proceed to payment.', "I'll scroll down for more results.",
    'Let me compare the top 3 options.', "I'll enter the shipping details.",
    'Let me apply the discount code.', "I'll navigate to the checkout page.",
    'Let me select the 1kg variant.', "I'll confirm the booking now.",
    'Let me fill in the guest details.', "I'll try searching with different keywords.",
    'Let me dismiss this popup first.', "I'll open the product in a new tab.",
    'Let me change the delivery address.',
  ];
  for (const o of obs) {
    for (const m of pickN(mid, 3)) {
      for (const a of pickN(act, 2)) {
        vecs.push([`${o} ${m} ${a}`, true, 'complex-multi']);
      }
    }
  }
  return vecs;
}

// ─── ALLOW: Rich product comparisons ────────────────────────────────────────
function genRichProductInfo(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const p of PRODUCTS) {
    const price = sPick(PRICES);
    const rating = sPick(RATINGS);
    const feat1 = sPick(FEATURES);
    const feat2 = sPick(FEATURES);
    vecs.push([`${p} — ${price} | ${rating} | ${feat1}, ${feat2}`, false, 'rich-product']);
    vecs.push([`${p}: ${price} after discount, ${rating} rating, ${feat1}`, false, 'rich-product']);
    vecs.push([`${p} (${price}) — Highlights: ${feat1}, ${feat2}`, false, 'rich-product']);
  }
  // Comparison sentences
  for (let i = 0; i < PRODUCTS.length - 1; i += 2) {
    const p1 = PRODUCTS[i], p2 = PRODUCTS[i + 1];
    vecs.push([`${p1} (${sPick(PRICES)}) vs ${p2} (${sPick(PRICES)})`, false, 'rich-product']);
    vecs.push([`Between ${p1} and ${p2}, ${p1} has better reviews`, false, 'rich-product']);
  }
  // Hotel comparisons
  for (let i = 0; i < HOTELS.length - 1; i += 2) {
    const h1 = HOTELS[i], h2 = HOTELS[i + 1];
    vecs.push([`${h1} (${sPick(PRICES)}/night) vs ${h2} (${sPick(PRICES)}/night)`, false, 'rich-product']);
  }
  return vecs;
}

// ─── ALLOW: Status updates (user-friendly phrasing) ─────────────────────────
function genUserStatusUpdates(): TestVector[] {
  const vecs: TestVector[] = [];
  const templates = [
    'Searching Flipkart for {product}...',
    'Found {n} results for "{product}" under {price}',
    'Adding {product} ({price}) to your cart...',
    'Proceeding to checkout for your order of {n} items',
    'Applying coupon code for {product}...',
    'Calculating delivery charges to {address}...',
    'Checking room availability at {hotel} for March 25-27...',
    'Reserving your room at {hotel}...',
    'Your {product} order is being processed...',
    'Confirming your booking at {hotel}...',
    'Setting up delivery to {address}...',
    'Verifying payment for {price}...',
  ];
  for (const tmpl of templates) {
    // "Proceeding to..." triggers the -ing action pattern
    const isSuppressed = tmpl.startsWith('Proceeding to ');
    for (const prod of pickN(PRODUCTS, 5)) {
      for (const price of pickN(PRICES, 3)) {
        const msg = tmpl
          .replace('{product}', prod)
          .replace('{price}', price)
          .replace('{n}', String(Math.floor(seededRandom() * 10) + 1))
          .replace('{address}', sPick(ADDRESSES))
          .replace('{hotel}', sPick(HOTELS));
        vecs.push([msg, isSuppressed, 'user-status-update']);
      }
    }
  }
  return vecs;
}

// ─── ALLOW: Detailed confirmations with IDs ─────────────────────────────────
function genDetailedConfirmations(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const name of USER_NAMES) {
    for (const id of ORDER_IDS) {
      vecs.push([`${name}, your order ${id} has been placed!`, false, 'detailed-confirm']);
      vecs.push([`Order ${id} confirmed. Delivery to ${sPick(ADDRESSES)}`, false, 'detailed-confirm']);
    }
    for (const h of pickN(HOTELS, 3)) {
      vecs.push([`${name}, your booking at ${h} is confirmed!`, false, 'detailed-confirm']);
    }
    for (const p of pickN(PRODUCTS, 3)) {
      vecs.push([`${name}, ${p} has been added to your cart`, false, 'detailed-confirm']);
    }
  }
  return vecs;
}

// ─── ALLOW: Multi-sentence user-facing (results + question) ─────────────────
function genUserMultiSentence(): TestVector[] {
  const vecs: TestVector[] = [];
  const resultParts = [
    'I found 5 options matching your budget.',
    'Here are the top wireless earbuds under ₹2,000.',
    'There are 3 hotels available for your dates.',
    'Your cart total is ₹450.',
    'The order has been placed successfully.',
    'I found a great deal on this item.',
    'This product has excellent reviews.',
    'The price dropped to ₹999 this week.',
    'Blinkit has 4 dal options in stock.',
    'All 3 hotels have free cancellation.',
  ];
  const questionParts = [
    'Would you like to proceed?',
    'Which one do you prefer?',
    'Should I add it to your cart?',
    'Do you want to see more options?',
    'Would you like to book this?',
    'Do you want express or standard delivery?',
    'Shall I apply the available coupon?',
    'Would you like the 500g or 1kg pack?',
    'Is this the right product?',
    'Do you want me to compare these?',
  ];
  // Some resultParts trigger narration patterns (observational "there are/is...", "this product has...")
  const suppressedResults = new Set([
    'There are 3 hotels available for your dates.',
    'This product has excellent reviews.',
  ]);
  for (const r of resultParts) {
    const isSuppressed = suppressedResults.has(r);
    for (const q of questionParts) {
      vecs.push([`${r} ${q}`, isSuppressed, 'user-multi-sentence']);
    }
  }
  return vecs;
}

// ─── ALLOW: Payment related messages ────────────────────────────────────────
function genPaymentMessages(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const pm of PAYMENT_METHODS) {
    for (const price of pickN(PRICES, 5)) {
      vecs.push([`Pay ${price} via ${pm}?`, false, 'payment']);
      vecs.push([`Payment of ${price} via ${pm} was successful!`, false, 'payment']);
      vecs.push([`${pm} payment of ${price} failed. Please try again.`, false, 'payment']);
    }
  }
  const payMsgs = [
    'Your UPI ID has been verified',
    'Redirecting to your bank for payment...',
    'Payment is being processed, please wait...',
    'Refund of ₹1,299 initiated to your account',
    'EMI of ₹299/month for 6 months selected',
    'No-cost EMI available on this purchase',
    'Cashback of ₹100 will be credited within 24 hours',
    'Your wallet balance is ₹500 — use it for this order?',
    'Split payment: ₹500 from wallet + ₹799 from UPI',
    'Invoice will be sent to your email after payment',
  ];
  for (const m of payMsgs) {
    vecs.push([m, false, 'payment']);
  }
  return vecs;
}

// ─── SUPPRESS: Reasoning with product-specific content ──────────────────────
function genReasoningWithProducts(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const p of pickN(PRODUCTS, 15)) {
    vecs.push([`We need to search for ${p} on Flipkart`, true, 'reasoning-product']);
    vecs.push([`We should add ${p} to the cart`, true, 'reasoning-product']);
    vecs.push([`We already have ${p} in the search results`, true, 'reasoning-product']);
    vecs.push([`But the budget doesn't cover ${p}`, true, 'reasoning-product']);
    vecs.push([`Since ${p} is available, let's proceed`, false, 'reasoning-product']);
    vecs.push([`However ${p} is out of stock`, false, 'reasoning-product']);
    vecs.push([`Note that ${p} has low reviews`, true, 'reasoning-product']);
  }
  // Hotels starting with "The" match the conjunction regex (^since\s+the )
  const conjMatchWords = new Set(['the', 'if', 'we', 'it', 'user', 'product', 'budget', 'item', 'items', 'they', 'this']);
  for (const h of pickN(HOTELS, 10)) {
    const firstWord = h.split(' ')[0].toLowerCase();
    const sinceHoweverMatch = conjMatchWords.has(firstWord);
    vecs.push([`We need to book ${h} for the user`, true, 'reasoning-product']);
    vecs.push([`We should check availability at ${h}`, true, 'reasoning-product']);
    vecs.push([`Since ${h} is within budget, proceed`, sinceHoweverMatch, 'reasoning-product']);
    vecs.push([`However ${h} has no rooms for these dates`, sinceHoweverMatch, 'reasoning-product']);
  }
  return vecs;
}

// ─── SUPPRESS: Observation + every filler × every page element ──────────────
function genFillerPageObservations(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const f of FILLER) {
    for (const p of PAGES) {
      for (const v of pickN(PAGE_VERBS, 3)) {
        vecs.push([`${f} the ${p} ${v} correctly`, true, 'filler-page']);
      }
    }
  }
  return vecs;
}

// ─── SUPPRESS: "I've <verb>" × more targets ─────────────────────────────────
function genIveExpanded(): TestVector[] {
  const vecs: TestVector[] = [];
  const expandedTargets = [
    ...TARGETS,
    'the guest name', 'the email field', 'the phone number field',
    'the billing address', 'the room type', 'the payment method',
    'the coupon code', 'the delivery slot', 'the gift wrapping option',
    'the special instructions', 'the loyalty points', 'the review form',
  ];
  for (const v of IVE_VERBS) {
    for (const t of expandedTargets) {
      vecs.push([`I've ${v} ${t}`, true, 'ive-expanded']);
    }
  }
  return vecs;
}

// ─── ALLOW: Cart-related user messages ──────────────────────────────────────
function genCartMessages(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const p of PRODUCTS) {
    const price = sPick(PRICES);
    vecs.push([`${p} (${price}) added to cart`, false, 'cart']);
    vecs.push([`Removed ${p} from your cart`, false, 'cart']);
    vecs.push([`${p} quantity updated to 2`, false, 'cart']);
    vecs.push([`${p} is no longer available — removed from cart`, false, 'cart']);
  }
  for (let n = 1; n <= 10; n++) {
    const total = sPick(PRICES);
    vecs.push([`Your cart: ${n} item${n > 1 ? 's' : ''}, total ${total}`, false, 'cart']);
    vecs.push([`Cart updated: ${n} item${n > 1 ? 's' : ''} — ${total}`, true, 'cart']);
  }
  vecs.push(['Your cart is empty', false, 'cart']);
  vecs.push(['Cart cleared', false, 'cart']);
  vecs.push(['Minimum order amount not met — add ₹60 more', false, 'cart']);
  return vecs;
}

// ─── ALLOW: Delivery/shipping user messages ─────────────────────────────────
function genDeliveryMessages(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const addr of ADDRESSES) {
    for (const dt of DELIVERY_TIMES) {
      vecs.push([`Delivery to ${addr} in ${dt}`, false, 'delivery']);
      vecs.push([`Estimated arrival at ${addr}: ${dt}`, false, 'delivery']);
    }
    vecs.push([`Delivering to: ${addr}`, false, 'delivery']);
    vecs.push([`Delivery not available at ${addr}`, false, 'delivery']);
  }
  const deliveryMsgs = [
    'Your order is out for delivery!',
    'Delivery partner assigned: Rahul (arriving in 8 min)',
    'Your package was delivered at 2:35 PM',
    'Delivery rescheduled to tomorrow',
    'Express delivery selected — ₹20 extra',
    'Standard delivery — free, arrives by March 25',
    'Same-day delivery available for ₹49',
    'Your delivery partner is on the way',
    'Package picked up from the store',
    'Delivery attempted — no one was home',
  ];
  for (const m of deliveryMsgs) {
    vecs.push([m, false, 'delivery']);
  }
  return vecs;
}

// ─── ALLOW: Coupon/offer messages ───────────────────────────────────────────
function genCouponMessages(): TestVector[] {
  const vecs: TestVector[] = [];
  const coupons = [
    'SAVE10', 'FIRST50', 'FLAT200', 'WELCOME', 'DIWALI25',
    'NEWUSER', 'FESTIVE15', 'BLINKIT50', 'SWIGGY30', 'HOTEL10',
  ];
  for (const c of coupons) {
    for (const price of pickN(PRICES, 4)) {
      vecs.push([`Coupon ${c} applied — you saved ${price}!`, false, 'coupon']);
      vecs.push([`Use code ${c} to save ${price} on your order`, false, 'coupon']);
    }
    vecs.push([`Coupon ${c} is expired`, false, 'coupon']);
    vecs.push([`Coupon ${c} requires minimum order of ₹500`, false, 'coupon']);
    vecs.push([`${c} applied successfully!`, false, 'coupon']);
  }
  return vecs;
}

// ─── ALLOW: Review/rating user messages ─────────────────────────────────────
function genReviewMessages(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const p of PRODUCTS) {
    const rating = sPick(RATINGS);
    const reviews = Math.floor(seededRandom() * 50000) + 100;
    vecs.push([`${p}: ${rating} from ${reviews.toLocaleString()} reviews`, false, 'review']);
    vecs.push([`${p} has ${rating} rating (${reviews.toLocaleString()} reviews)`, false, 'review']);
  }
  for (const h of HOTELS) {
    const rating = sPick(RATINGS);
    vecs.push([`${h}: ${rating} — "Excellent location and service"`, false, 'review']);
    vecs.push([`${h} rated ${rating} by ${Math.floor(seededRandom() * 5000)} guests`, false, 'review']);
  }
  return vecs;
}

// ─── SUPPRESS: More reasoning × address combos ─────────────────────────────
function genReasoningWithAddresses(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const addr of ADDRESSES) {
    vecs.push([`We need to set the delivery location to ${addr}`, true, 'reasoning-addr']);
    vecs.push([`The user's address is ${addr}, so we skip asking`, true, 'reasoning-addr']);
    vecs.push([`Since the address ${addr} is already set, proceed`, true, 'reasoning-addr']);
    vecs.push([`But the user wants delivery to ${addr}, not here`, true, 'reasoning-addr']);
    vecs.push([`Address is already provided: ${addr}`, true, 'reasoning-addr']);
    vecs.push([`Let's set the location to ${addr} first`, false, 'reasoning-addr']);
  }
  return vecs;
}

// ─── SUPPRESS: "It <verb>" expanded ─────────────────────────────────────────
function genItVerbExpanded(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const v of IT_VERBS) {
    for (const t of IT_TAILS) {
      vecs.push([`It ${v} ${t}`, true, 'it-verb-expanded']);
    }
  }
  return vecs;
}

// ─── ALLOW: Availability / stock messages ───────────────────────────────────
function genAvailabilityMessages(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const p of PRODUCTS) {
    vecs.push([`${p} is in stock`, false, 'availability']);
    vecs.push([`${p} — only 3 left!`, false, 'availability']);
    vecs.push([`${p} is back in stock`, false, 'availability']);
    vecs.push([`${p} ships in 2-3 business days`, false, 'availability']);
    vecs.push([`${p} available in: Black, White, Blue`, false, 'availability']);
    vecs.push([`${p} — next restock expected in 5 days`, false, 'availability']);
  }
  for (const h of HOTELS) {
    vecs.push([`${h} — 2 rooms left at this price`, false, 'availability']);
    vecs.push([`${h} has availability for your dates`, false, 'availability']);
    vecs.push([`${h} — sold out for March 25`, false, 'availability']);
    vecs.push([`${h} — last room available!`, false, 'availability']);
  }
  return vecs;
}

// ─── ALLOW: Warranty / return / policy messages ─────────────────────────────
function genPolicyMessages(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const p of pickN(PRODUCTS, 15)) {
    vecs.push([`${p}: 1-year manufacturer warranty`, false, 'policy']);
    vecs.push([`${p}: 7-day replacement guarantee`, false, 'policy']);
    vecs.push([`${p}: 30-day return window`, false, 'policy']);
    vecs.push([`${p}: No-questions-asked returns for 10 days`, false, 'policy']);
  }
  for (const h of pickN(HOTELS, 10)) {
    vecs.push([`${h}: Free cancellation until March 23`, false, 'policy']);
    vecs.push([`${h}: Non-refundable rate — 15% cheaper`, false, 'policy']);
    vecs.push([`${h}: Check-in 2 PM, Check-out 11 AM`, false, 'policy']);
    vecs.push([`${h}: Breakfast included in room rate`, false, 'policy']);
    vecs.push([`${h}: Late check-out available on request`, false, 'policy']);
  }
  return vecs;
}

// ─── ALLOW: Spec / feature combos for products ─────────────────────────────
function genSpecMessages(): TestVector[] {
  const vecs: TestVector[] = [];
  for (const p of PRODUCTS) {
    for (const f1 of pickN(FEATURES, 3)) {
      for (const f2 of pickN(FEATURES, 2)) {
        if (f1 !== f2) {
          vecs.push([`${p}: ${f1}, ${f2}`, false, 'spec']);
        }
      }
    }
  }
  return vecs;
}

// ═══════════════════════════════════════════════════════════════════════════════
// ASSEMBLE ALL VECTORS
// ═══════════════════════════════════════════════════════════════════════════════

export function generateAllVectors(): TestVector[] {
  _seed = 42; // reset seed for reproducibility
  const all: TestVector[] = [
    // SUPPRESS (internal)
    ...genToolLabels(),
    ...genObservational(),
    ...genObservationalExpanded(),
    ...genAction(),
    ...genActionExpanded(),
    ...genStatus(),
    ...genThirdPerson(),
    ...genBrowserInternals(),
    ...genSelfDirectedInternal(),
    ...genReasoning(),
    ...genReasoningWithProducts(),
    ...genReasoningWithAddresses(),
    ...genFillerPrefixed(),
    ...genFillerPageObservations(),
    ...genDoubleFillerNarration(),
    ...genMultiSentence(),
    ...genComplexMultiSentence(),
    ...genIveExpanded(),
    ...genItVerbExpanded(),
    // ALLOW (user-facing)
    ...genUserResults(),
    ...genUserQuestions(),
    ...genConfirmations(),
    ...genPriceInfo(),
    ...genUserErrors(),
    ...genGeneralUserFacing(),
    ...genRichProductInfo(),
    ...genUserStatusUpdates(),
    ...genDetailedConfirmations(),
    ...genUserMultiSentence(),
    ...genPaymentMessages(),
    ...genCartMessages(),
    ...genDeliveryMessages(),
    ...genCouponMessages(),
    ...genReviewMessages(),
    ...genAvailabilityMessages(),
    ...genPolicyMessages(),
    ...genSpecMessages(),
  ];
  return all;
}

// Quick stats when imported
const _all = generateAllVectors();
const _suppress = _all.filter(([, s]) => s).length;
const _allow = _all.filter(([, s]) => !s).length;
export const VECTOR_STATS = {
  total: _all.length,
  suppress: _suppress,
  allow: _allow,
};
